language: cpp
sudo: required
git:
  depth: 3
env: PYTHONPATH=$PYTHONPATH:/usr/local/cmake-3.9.2/bin/
cache:
  pip: true
  directories:
    - release
    - blockscipy/build
    - .mtime_cache
    - $HOME/.local
    - $HOME/.cache/pip
matrix:
  include:
    - stage: Build C++ Library
      dist: xenial
      before_install: .travis/build_ubuntu_cpp.sh
      install: .travis/compile_ubuntu_cpp.sh
      script: .travis/test_parser.sh
    - os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - cmake
            - jsoncpp
            - libjson-rpc-cpp
            - boost
            - openssl
            - jemalloc
            - zstd
            - automake
            - libtool
            - google-sparsehash
            - lz4
            - python3
      before_install: .travis/build_osx_cpp.sh
      install: .travis/compile_osx_cpp.sh
      script: .travis/test_parser.sh
    - stage: Build Python Module
      dist: xenial
      before_install:
        - .travis/build_ubuntu_cpp.sh
        - .travis/build_ubuntu_python.sh
      install:
        - .travis/compile_ubuntu_cpp.sh
        - .travis/compile_ubuntu_python.sh
      script:
        - .travis/test_python.sh
        - .travis/generate_docs.sh
