export CFLAGS="$CFLAGS -I$PREFIX/include"
export CXXFLAGS="$CXXFLAGS -I$PREFIX/include"
export LDFLAGS="$LDFLAGS -L$PREFIX/lib"

mkdir -p build
cd build
cmake -LAH -DCMAKE_BUILD_TYPE="Release" -DJSONCPP_INCLUDE_DIRS=$PREFIX/include -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_PREFIX_PATH=${PREFIX} ..
 
VERBOSE=1 make install -j${CPU_COUNT}
